# Generated by Django 6.1 on 2026-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
